package sk.uniza.fri.gui;

import sk.uniza.fri.nacitavanie.Hrana;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * 12. 4. 2025 - 13:32
 *
 * @author matus
 */
public class UpravHranu extends JFrame {
    private JTextField cenaHranyTF;
    private JCheckBox zakazHranyCheckBox;
    private JButton ukonciEditaciuButton;
    private JButton potvrdZmenyButton;
    private JPanel rootComponent;
    private Hrana hrana;
    private IOACanvas platno;

    public UpravHranu(Hrana pHrana, IOACanvas pPlatno) {
        this.platno = pPlatno;
        this.hrana = pHrana;
        if (platno.isHranyAutomaticky()) {
            cenaHranyTF.setVisible(false);
        } else {
            cenaHranyTF.setVisible(true);
        }

        UpravHranu.this.cenaHranyTF.setText(String.valueOf(hrana.getCena()));

        if (this.hrana.jeZakazana()) {

            zakazHranyCheckBox.setSelected(true);

        } else {

            zakazHranyCheckBox.setSelected(false);

        }
        this.ukonciEditaciuButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                UpravHranu.this.dispose();
            }
        });

        this.potvrdZmenyButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                UpravHranu.this.hrana.setCena(Double.parseDouble(cenaHranyTF.getText()));

                if (zakazHranyCheckBox.isSelected()) {
                    UpravHranu.this.hrana.setZakaz(true);

                } else {
                    UpravHranu.this.hrana.setZakaz(false);
                }
                UpravHranu.this.platno.repaint();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootComponent = new JPanel();
        rootComponent.setLayout(new GridBagLayout());
        cenaHranyTF = new JTextField();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rootComponent.add(cenaHranyTF, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rootComponent.add(spacer1, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Cena hrany");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        rootComponent.add(label1, gbc);
        ukonciEditaciuButton = new JButton();
        ukonciEditaciuButton.setText("Ukonci editaciu");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rootComponent.add(ukonciEditaciuButton, gbc);
        potvrdZmenyButton = new JButton();
        potvrdZmenyButton.setText("Potvrd zmeny");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rootComponent.add(potvrdZmenyButton, gbc);
        zakazHranyCheckBox = new JCheckBox();
        zakazHranyCheckBox.setText("Zakaz hrany");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        rootComponent.add(zakazHranyCheckBox, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootComponent;
    }

}
