package sk.uniza.fri.gui;

import sk.uniza.fri.nacitavanie.TypVrchola;
import sk.uniza.fri.nacitavanie.Vrchol;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * 12. 4. 2025 - 13:32
 *
 * @author matus
 */
public class UpravVrchol extends JFrame {
    private JButton potvrdZmenyButton;
    private JButton ukonciUpravyButton;
    private JComboBox comboBox1;
    private JTextField poziadavkaTF;
    private JPanel rootComp;
    private JLabel poziadKapLabel;
    private Vrchol vrchol;
    private IOACanvas platno;

    public UpravVrchol(Vrchol upravovanyVrchol, IOACanvas pPlatno) {
        this.vrchol = upravovanyVrchol;
        this.platno = pPlatno;
        if (vrchol.getTypVrchola() == TypVrchola.STREDISKO) {
            poziadKapLabel.setText("Kapacita vrchola: ");
        } else {
            poziadKapLabel.setText("Požiadavka vrchola: ");
        }

        this.poziadavkaTF.setText(String.valueOf(vrchol.getPoziadavkaOrKapacita()));
        this.comboBox1.setSelectedIndex(vrchol.getTypVrchola().getCislo());
        this.potvrdZmenyButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                UpravVrchol.this.vrchol.setPoziadavkaOrKapacita(Double.parseDouble(poziadavkaTF.getText()));
                int idStrediska = UpravVrchol.this.platno.getSiet().getIDStrediska();
                if (idStrediska != -1 && TypVrchola.valueOf((String) comboBox1.getSelectedItem()).equals(TypVrchola.STREDISKO)) {
                    UpravVrchol.this.platno.getSiet().getVrcholy().get(idStrediska).setTypVrchola(TypVrchola.NESPECIFIKOVANY);
                }
                UpravVrchol.this.vrchol.setTypVrchola(TypVrchola.valueOf((String) comboBox1.getSelectedItem()));
                UpravVrchol.this.platno.getSiet().upravVrchol(UpravVrchol.this.vrchol);
                UpravVrchol.this.platno.repaint();
            }
        });

        this.ukonciUpravyButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                UpravVrchol.this.dispose();
            }
        });


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootComp = new JPanel();
        rootComp.setLayout(new GridBagLayout());
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rootComp.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        rootComp.add(spacer2, gbc);
        potvrdZmenyButton = new JButton();
        potvrdZmenyButton.setText("Potvrd zmeny");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rootComp.add(potvrdZmenyButton, gbc);
        ukonciUpravyButton = new JButton();
        ukonciUpravyButton.setText("Ukonci upravy");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rootComp.add(ukonciUpravyButton, gbc);
        comboBox1 = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("NESPECIFIKOVANY");
        defaultComboBoxModel1.addElement("ZAKAZNIK");
        defaultComboBoxModel1.addElement("STREDISKO");
        comboBox1.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rootComp.add(comboBox1, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Typ vrchola");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        rootComp.add(label1, gbc);
        poziadavkaTF = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rootComp.add(poziadavkaTF, gbc);
        poziadKapLabel = new JLabel();
        poziadKapLabel.setText("Poziadavka vrchola");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        rootComp.add(poziadKapLabel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootComp;
    }

}
