package sk.uniza.fri.gui;

import sk.uniza.fri.nacitavanie.Siet;
import sk.uniza.fri.nacitavanie.Ukladac;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * 12. 4. 2025 - 13:32
 *
 * @author matus
 */
public class UvodneOkno extends JFrame {
    private JPanel hlOkno;
    private JButton nacitajZoSuboruButton;
    private JButton grafickeZobrazenieButton;
    private JButton ukonciAplikaciuButton;
    private JTextField suborVrcholyTF;
    private JTextField subroHranyTF;
    private JButton nacitajZDefaultSuborovButton;
    private Siet siet;


    public UvodneOkno() {
        this.siet = new Siet();

        this.nacitajZoSuboruButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                try {
                    UvodneOkno.this.siet.nacitaj(
                            UvodneOkno.this.subroHranyTF.getText(),
                            UvodneOkno.this.suborVrcholyTF.getText()
                    );
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(
                            UvodneOkno.this,
                            "Chyba pri načítaní súborov! Skontrolujte, či ste zadali správne cesty.",
                            "Chyba načítania",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }
        });


        this.grafickeZobrazenieButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                GrafickyEditor grafickyEditor = new GrafickyEditor(siet);
                grafickyEditor.setSize(1000, 800);
                grafickyEditor.setContentPane(grafickyEditor.$$$getRootComponent$$$());
                grafickyEditor.pack();
                grafickyEditor.setVisible(true);
            }
        });

        this.ukonciAplikaciuButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                UvodneOkno.this.dispose();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        hlOkno = new JPanel();
        hlOkno.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Možnosti:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        hlOkno.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        hlOkno.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        hlOkno.add(spacer2, gbc);
        nacitajZoSuboruButton = new JButton();
        nacitajZoSuboruButton.setText("Načítaj zo zadanych suborov");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        hlOkno.add(nacitajZoSuboruButton, gbc);
        grafickeZobrazenieButton = new JButton();
        grafickeZobrazenieButton.setText("Graficke zobrazenie/editovanie");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        hlOkno.add(grafickeZobrazenieButton, gbc);
        ukonciAplikaciuButton = new JButton();
        ukonciAplikaciuButton.setText("Ukonči aplikáciu");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        hlOkno.add(ukonciAplikaciuButton, gbc);
        suborVrcholyTF = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        hlOkno.add(suborVrcholyTF, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Súbor s vrcholmi");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        hlOkno.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Súbor s hranami");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        hlOkno.add(label3, gbc);
        subroHranyTF = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        hlOkno.add(subroHranyTF, gbc);
        nacitajZDefaultSuborovButton = new JButton();
        nacitajZDefaultSuborovButton.setText("Nacitaj z default suborov");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        hlOkno.add(nacitajZDefaultSuborovButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return hlOkno;
    }

}
